import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless: true, channel: 'msedge' });
try {
  for (const width of [1280, 390]) {
    const context = await browser.newContext({ viewport: { width, height: 900 }, reducedMotion: 'reduce', httpCredentials: { username: 'staff', password: 'synthetic-preview-test' } });
    const page = await context.newPage(); page.setDefaultTimeout(30000);
    const errors = []; page.on('pageerror', (e) => errors.push(e.message));
    const external = []; page.on('request', (request) => { if (!new URL(request.url()).hostname.match(/^(127\.0\.0\.1|localhost)$/)) external.push(request.url()); });
    await page.goto(process.env.SMOKE_URL || 'http://127.0.0.1:3017');
    await page.getByRole('button', { name: 'Start estimate', exact: true }).click();
    const input = page.getByLabel('Southern California city or neighborhood', { exact: true });
    await input.fill('No such city xyz');
    await page.locator('#location-status').filter({ hasText: 'No matching city' }).waitFor();
    await page.getByRole('button', { name: 'Continue', exact: true }).click();
    await page.getByRole('alert').filter({ hasText: 'Select a city and county' }).waitFor();
    await input.fill('Anza');
    await page.getByRole('button', { name: 'Anza, Imperial County, CA', exact: true }).waitFor();
    await page.getByRole('button', { name: 'Anza, Riverside County, CA', exact: true }).waitFor();
    await input.fill('Lake Forest');
    await page.getByRole('button', { name: 'Lake Forest, Orange County, CA', exact: true }).click();
    await page.locator('#location-status').filter({ hasText: 'Staff review required' }).waitFor();
    assert.equal(await page.locator('input[name=distanceTier]').count(), 0);
    assert(!(await page.locator('#location-status').innerText()).includes('not configured'));
    await page.screenshot({ path: join(tmpdir(), `whs-local-city-${width}.png`), fullPage: true });
    await input.fill('Lake Forest edited');
    await page.getByRole('button', { name: 'Continue', exact: true }).click();
    await page.getByRole('alert').filter({ hasText: 'Select a city and county' }).waitFor();
    await input.fill('Lake Forest');
    await page.getByRole('button', { name: 'Lake Forest, Orange County, CA', exact: true }).click();
    await page.locator('#location-status').filter({ hasText: 'Staff review required' }).waitFor();
    await page.getByRole('button', { name: 'Continue', exact: true }).click();
    await page.getByRole('checkbox', { name: 'Furniture', exact: true }).check();
    await page.getByRole('checkbox', { name: 'Appliances', exact: true }).check();
    await page.getByRole('button', { name: 'Continue', exact: true }).click();
    await page.getByRole('radio', { name: 'Garage', exact: true }).check();
    await page.getByRole('radio', { name: 'Short carry', exact: true }).check();
    await page.getByRole('radio', { name: 'No stairs', exact: true }).check();
    await page.getByRole('button', { name: 'Continue', exact: true }).click();
    const image = await page.evaluate(() => { const c = document.createElement('canvas'); c.width = c.height = 1600; const x = c.getContext('2d'); x.fillStyle = '#dce8ef'; x.fillRect(0, 0, 1600, 1600); x.fillStyle = '#436451'; x.fillRect(200, 200, 500, 400); return c.toDataURL().split(',')[1]; });
    await page.locator('input[type=file]').setInputFiles(Array.from({ length: 10 }, (_, i) => ({ name: `synthetic-${i}.png`, mimeType: 'image/png', buffer: Buffer.from(image, 'base64') })));
    await page.waitForFunction(() => !document.querySelector('.stepActions button[type=submit]').disabled);
    await page.getByRole('button', { name: 'Continue', exact: true }).click();
    await page.locator('textarea[name=notes]').fill('Synthetic scope only. Nothing outside the photos.');
    assert((await page.locator('.reviewList').innerText()).includes('Staff review required'));
    assert((await page.locator('.reviewList').innerText()).includes('furniture, appliances'));
    const submitted = page.waitForRequest((req) => req.url().endsWith('/api/analyze'));
    const responded = page.waitForResponse((res) => res.url().endsWith('/api/analyze'));
    await page.getByRole('button', { name: 'Check review requirements', exact: true }).click();
    const request = await submitted;
    const form = await new Request('http://synthetic.test', { method: 'POST', headers: request.headers(), body: request.postDataBuffer() }).formData();
    assert.equal(form.get('workflow'), 'guided-city-v3'); assert.equal(form.get('cityId'), 'geonames:5364514');
    assert.equal(form.has('distanceTier'), false); assert.equal(form.has('locationToken'), false);
    assert.equal(form.getAll('photos').length, 10); assert(form.getAll('photos').reduce((n, p) => n + p.size, 0) <= 3.5 * 1024 * 1024);
    const result = await (await responded).json();
    assert.equal(result.status, 'needs_manager_review'); assert.equal(result.pricing, null); assert.equal(result.analysis, null);
    assert.equal(result.inputs.location.county, 'Orange County'); assert.equal(result.inputs.distanceTier, null);
    await page.getByRole('heading', { name: 'Manager review required', exact: true }).waitFor();
    assert.equal(await page.locator('.quoteBox').count(), 0);
    await page.getByText('Your photos and details are retained.', { exact: false }).waitFor();
    await page.screenshot({ path: join(tmpdir(), `whs-local-review-${width}.png`), fullPage: true });
    await page.getByRole('button', { name: 'Edit original details', exact: true }).click();
    assert.equal(await page.locator('textarea[name=notes]').inputValue(), 'Synthetic scope only. Nothing outside the photos.');
    assert((await page.locator('.reviewList').innerText()).includes('10 selected and optimized'));
    await page.getByRole('button', { name: 'Wade Home Services - start over', exact: true }).click();
    await page.getByRole('button', { name: 'Start estimate', exact: true }).click();
    assert.equal(await input.inputValue(), '');
    // A transient local endpoint error preserves the normal retry/no-tier behavior.
    await page.route('**/api/estimate-location?*', (route) => route.fulfill({ status: 503, json: { error: 'Synthetic local directory unavailable' } }));
    await input.fill('Lake Forest');
    await page.locator('#location-status').filter({ hasText: 'Synthetic local directory unavailable' }).waitFor();
    await page.unroute('**/api/estimate-location?*');
    await page.getByRole('button', { name: 'Retry location search', exact: true }).click();
    await page.getByRole('button', { name: 'Lake Forest, Orange County, CA', exact: true }).waitFor();
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    assert.deepEqual(errors, []); assert.deepEqual(external, []);
    await context.close();
  }
  console.log('PASS: desktop/mobile local directory, county disambiguation, free-text rejection, review-required selection, ten-photo optimization, real local API review response without pricing/model call, preserved details, reset and transient lookup failure/retry. No Maps/OpenAI/Sheets requests.');
} finally { await browser.close(); }
